eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}


# DB Configs
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: public
        hbm2ddl:
          import_files:
  kafka:
    bootstrap-servers: ${kafka-list-servers}
    template:
      default-topic: changeRouteAssignment-p01usw1prod

edulog:
  datasource:
    url: jdbc:postgresql://db-prod.usw1.karrostech.net:5432/Edulog
    username: karros_prod_admin
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGrx/wBTNFYFkMyWMs1zDiRAAAAezB5BgkqhkiG9w0BBwagbDBqAgEAMGUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbdsrRTlU6ozJEvsdAgEQgDjNLewA1V49MQQWNmqjsLYRDmsx+9K7TTNCaePFZ+qDLp0KS/Ock1Cvgg/T6hDEPBCdJqYByDDDnw=='
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 5
      test-on-borrow: true

# Spring Security configurations are required for this application to work with the
# Karrostech Security dependency included in pom.xml.
security.jwt:
  tokenExpirationTime: 120 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://karrostech.com
  # base 64 encoded signing key
  tokenSigningKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsh0GXHEy3S3jOX9QXXT8yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDWTMtLq5qBNuvpYAgEQgDvEFsvknk7vamQJiB5wJmwbF570MckoCVEqD8O7MVwpzzbK8pdXJ4dMDfFUeMcWL+eE/SaCae9u6QX4cQ=='
  secureAuthenticationEntryUrl: /api/**
  unsecurePathList: [/v2/api-docs/**, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /swagger-ui.html/**, /webjars/**, /swagger-resources/configuration/ui,
                     /swagger-resources/configuration/security, /manage/** ]
security.basic.enabled: false

kafka:
  applicationId: routeVehicleDriverMappingService
  consumer-group: routeVehicleDriverMappingService-consumer-group-p01usw1prod
  consumer:
    vehicleInfo: vehicle-info-p01usw1prod

hystrix.command.GetRouteAssignments.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.GetRouteAssignments.coreSize: 10
hystrix.threadpool.GetRouteAssignments.maximumSize: 500
hystrix.threadpool.GetRouteAssignments.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.GetRouteAssignmentsWithRun.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.GetRouteAssignmentsWithRun.coreSize: 10
hystrix.threadpool.GetRouteAssignmentsWithRun.maximumSize: 500
hystrix.threadpool.GetRouteAssignmentsWithRun.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.GetCurrentAssignment.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.GetCurrentAssignment.coreSize: 10
hystrix.threadpool.GetCurrentAssignment.maximumSize: 500
hystrix.threadpool.GetCurrentAssignment.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.getCurrentAssignmentV2.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.getCurrentAssignmentV2.coreSize: 10
hystrix.threadpool.getCurrentAssignmentV2.maximumSize: 500
hystrix.threadpool.getCurrentAssignmentV2.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.CreateRouteAssignments.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.CreateRouteAssignments.coreSize: 10
hystrix.threadpool.CreateRouteAssignments.maximumSize: 500
hystrix.threadpool.CreateRouteAssignments.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.CreateV2RouteAssignments.execution.isolation.thread.timeoutInMilliseconds: 15000
hystrix.threadpool.CreateV2RouteAssignments.coreSize: 10
hystrix.threadpool.CreateV2RouteAssignments.maximumSize: 500
hystrix.threadpool.CreateV2RouteAssignments.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.SynchronizeRouteAssignments.execution.isolation.thread.timeoutInMilliseconds: 3000
hystrix.threadpool.SynchronizeRouteAssignments.coreSize: 10
hystrix.threadpool.SynchronizeRouteAssignments.maximumSize: 500
hystrix.threadpool.SynchronizeRouteAssignments.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.v2SynchronizeRouteAssignments.execution.isolation.thread.timeoutInMilliseconds: 6000
hystrix.threadpool.v2SynchronizeRouteAssignments.coreSize: 10
hystrix.threadpool.v2SynchronizeRouteAssignments.maximumSize: 500
hystrix.threadpool.v2SynchronizeRouteAssignments.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.findAllRouteAssignmentByRouteCode.execution.isolation.thread.timeoutInMilliseconds: 6000
hystrix.threadpool.findAllRouteAssignmentByRouteCode.coreSize: 10
hystrix.threadpool.findAllRouteAssignmentByRouteCode.maximumSize: 500
hystrix.threadpool.findAllRouteAssignmentByRouteCode.allowMaximumSizeToDivergeFromCoreSize: true
