eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-demo.usw2.karrostech.net:1112/eureka/,http://eureka02-p01-demo.usw2.karrostech.net:1112/eureka/

spring.cloud.stream.bindings:
  input:
    destination: aggregateAVLEvents-p01usw2demo
    #destination: aggregateAVLEvents-LasVegasDemo-2019
  output:
    destination: run-sub-es-results-p01usw2demo

spring.cloud.stream.kafka.streams:
  binder:
    application-id: runDetectionNNet-p01usw2demo
    brokers: ${kafka-list-servers}

spring.cloud.stream.kafka.binder.autoAddPartitions: true
spring.cloud.stream.kafka.binder.autoCreateTopics: true
spring.cloud.stream.kafka.binder.minPartitionCount: 12
spring.cloud.stream.kafka.binder.replicationFactor: 3

spring.redis.host: redis-demo.usw2.karrostech.net
spring.redis.port: 6379
spring.redis.password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsP0dcMRb2ccR0M5OZ9u2QAAAAfDB6BgkqhkiG9w0BBwagbTBrAgEAMGYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5ZwTH/yi3i+KkGDHAgEQgDlZb3mBKRe9lvZ4savziOdKl57sdyDy7zH0flgd3GuayrFVgZ6X0It90pekXlX6ccRN3fTO0+dLXuE='

spring.redis.jedis.pool.max-active: 50
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 10
spring.redis.jedis.pool.max-idle: 30

spring.redis.vehicle.host: ${spring.redis.host}
spring.redis.vehicle.port: ${spring.redis.port}
spring.redis.vehicle.database: 4
spring.redis.vehicle.password: ${spring.redis.password}

es:
  hosts:
    -
      name: ES-AWS
      url: ${elasticSearch.aws.url}
      username:
      password:
      protocol: https
      connectionTimeout: 10000
      socketTimeout: 60000
      parallelESCountThreads: 100
      port: ${elasticSearch.aws.port}
    -
      name: ES-CLUSTER
      url: ${elasticSearch.cloud.url}
      username: ${elasticSearch.cloud.username}
      password: ${elasticSearch.cloud.password}
      protocol: https
      connectionTimeout: 10000
      socketTimeout: 60000
      parallelESCountThreads: 100
      port: ${elasticSearch.cloud.port}
  tenantIndex:
    indexName: tenant
    type: doc
  directionIndex: rundirections
  realTimeVehicleEvent:
    indexName: realtimevehiclesevents
    type: doc

detection:
  oldRunDeleteThreshold: 1h
  weights:
    consecutive: 1
    missed: -.1
    total: 1
