eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false 
eureka.client.enabled: false 

management:
  health:
    redis:
      enabled: false

# API Keys that are acceptable
validApiKeys: ${apiKeys}

audit:
  loggedBy: ${spring.application.name}
  enabled: true
  methods: POST,PUT,DELETE,PATCH, GET
  defaultIgnoredEndpoints:
  defaultStoreResponseBody: true
  defaultStoreRequestBody: true
  #This header will be added before Zuul routing, but Zuul auto converts to lower case, so the value should be in lower case
  xTrkHeaderKeyName: x-trk-id
  customRequests:
    -
      endpoints: /api/v1/vehicleStatus, /api/0.2/events/vehicleId?vehicleId=
      methods: GET
      enabled: false
      storeRequestBody: true
      storeResponseBody: false
    -
      endpoints: /search, /bulksearch, /export
      methods: POST, GET
      enabled: true
      storeRequestBody: true
      storeResponseBody: false

keycloak:
  cors: true
  realm: Edulog
  auth-server-url: https://aaa.use2.karrostech.net/auth
  ssl-required: external
  resource: mission-control-v2
  bearer-only: false
  credentials:
    secret: 39aa8bac-c2ec-429c-86b0-bfe38bd991af
  policy-enforcer-config:
    lazy-load-paths: true
    paths:
      - path: /info
        name: server-info-check
        enforcement-mode: DISABLED
      - path: /health
        name: server-health-check
        enforcement-mode: DISABLED
      - path: /*
        methods:
          - method: OPTIONS
        name: ignore-options-check
        enforcement-mode: DISABLED
  securityConstraints:
    - authRoles:
        - System Admin
        - System User
      securityCollections:
        - name: Resource Management
          patterns:
            - /api/*
  use-resource-role-mappings: true
  enabled: false

zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  ribbonIsolationStrategy: THREAD
  routes:
    inventoryService:
      path: /api/*/equipment/**
      serviceId: INVENTORYSERVICE
      stripPrefix: false
    featureflagservice:
      path: /api/*/ff/**
      serviceId: FEATUREFLAGSERVICE
      stripPrefix: false
    athenaETLService:
      path: /api/*/athenaetl/**
      serviceId: ATHENAETLSERVICE
      stripPrefix: false
  retryable: true
  