# Property file for local use. Will be used if spring.profiles.active is not set

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  bootstrap: 10.20.20.121:9092
  consumer:
    groupId: test-calampRawData-group
    topic: calampRawData
  producer:
    topic: calampDecodedMessage-p01use2dev
    errorTopic: rawError
