eureka:
  instances: http://eureka01-p01-dev.use2.karrostech.net:1112/eureka/,http://eureka02-p01-dev.use2.karrostech.net:1112/eureka/

kafka:
  servers: 10.20.20.121:9092
  bootstrap-server: 10.20.20.121:9092
  athena-bootstrap-msk: b-1.athenamsk.eg7z0i.c3.kafka.us-east-2.amazonaws.com:9092, b-2.athenamsk.eg7z0i.c3.kafka.us-east-2.amazonaws.com:9092

elasticSearch:
  logAggregation:
    url: 2ccf0579872b4a3aad8aeda90137dfd6.us-east-1.aws.found.io
    username: elastic
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGcaZWtA+fj+eRZQ7T7FMW+AAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAt4chiKot4qvp5lGAgEQgDMXt7mSjzH4tyl1w4IVqfSuZky+IjABks9nHqTb/H6Umc6PHXYiCpCslksWG4gpIFtxG98='
    port: 9243
  cloud:
    url: 265eb3574a7146a791b71965a2e378fa.us-west-2.aws.found.io
    username: elastic
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGnZdnV5uwcWTG3MvEK/ys3AAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtC/iBkI5cxQeg5qTAgEQgDNmCgz5QqPD5Ks2FGA5G0QwRi4FDKZcEeN4kHP+NLVIRiV8Urca0hKVoNr4KFp26Ugya8w='
    port: 9243
  aws:
    url: vpc-p01use2dev-ba2ebrzmg3m3wtnpn7vrhlub2y.us-east-2.es.amazonaws.com
    username:
    password:
    port: 443
  awsv7:
    url: vpc-p01use2dev-7-3ga6y7r4qsd4mzrwyyrjtnpwra.us-east-2.es.amazonaws.com
    username:
    password:
    port: 443

rds:
  dataSource:
    url: jdbc:postgresql://db-dev.use2.karrostech.net:5432/Edulog
    username: karros
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAF1tjwR9jL3pwqiDVUwBkrMAAAAfTB7BgkqhkiG9w0BBwagbjBsAgEAMGcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsxulA/cLhH/DVWPIAgEQgDqhMN6j5wKMj/5H4HHEW1O3vodBUEabssk2Sv2Nzi+pp0jItHq4QaFWNmj8PCQpFuSSjmYKWKC4d31K'

edulog:
  datasource:
    url: jdbc:postgresql://db-dev.use2.karrostech.net:5432/Edulog
    username: karros
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAF1tjwR9jL3pwqiDVUwBkrMAAAAfTB7BgkqhkiG9w0BBwagbjBsAgEAMGcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsxulA/cLhH/DVWPIAgEQgDqhMN6j5wKMj/5H4HHEW1O3vodBUEabssk2Sv2Nzi+pp0jItHq4QaFWNmj8PCQpFuSSjmYKWKC4d31K'
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      test-on-borrow: true

security:
  jwt:
    issuer: http://karrostech.com
    signature: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsh0GXHEy3S3jOX9QXXT8yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDWTMtLq5qBNuvpYAgEQgDvEFsvknk7vamQJiB5wJmwbF570MckoCVEqD8O7MVwpzzbK8pdXJ4dMDfFUeMcWL+eE/SaCae9u6QX4cQ=='
    duration: # minutes
      token: 120
      refreshToken: 60
    enableKeycloakJWT: true
    keycloakTokenIssuer: karros-keycloak
    keycloakPublicKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAF/Eobopmgfi1AAZDoGNA95AAAB8DCCAewGCSqGSIb3DQEHBqCCAd0wggHZAgEAMIIB0gYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAw0N3gWucKLKFxf0csCARCAggGjm6Tc1ty3r6WFxBc72IP2ncg4RYa4+16AhGnK40JKC5VtD+sZD1164TCAjtAHJ81eUPO1/Ni1Rk7dQ5qed4wRTMuHzhZGONTbWx/cSdKK4SauJqVknKODMTK/8DI7J07U3wYXLiDY8Th9tDpiTX9Lms+LmsOrZg3Ao7mLdEJAVTLC95AG+G3B0UviX5SaWEjzH1x/6JH78oMoPEFiisy551G2s/lFHrLGs2Vi32QrQR7BWJnutFZ0ZLRgjg50k6AfaH7ea483PzWybkvfFm2Nu6UNByiNWrGOIVY0VMZPAOVVXOoYzp14fDFcEB5vg5ewFImCDd1Ygek09XSoNdb/TRJjdamaYEYoF9LKI40ue/E9P437hhODyH0xXCv9kJ4CIEbZKfn0JiPkh8lDclNL04P2sXsvdbxZefxHL6M7U8UHXcr583P3GJYNTOMcDWoiS+4QbgmMOBPqLQyBNj2QC2YDyPbqCK16vR9AtAOLtpLT3BeRUFifSDGGwO46FEbsw0ncGjUmpzYMiVRtk7T046vbHqST6vWSUH2V3PBaTYqchlM='

auth:
  credentials:
    clientId: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAH+B2Aa2gdAV4uOodo4dgGcAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHCp+JqK/s8hu1hbWwIBEIBDZVeV3Vpkfy+yrqL0EfYIio/AT3okxFgUxBJzkX8D4XMNgpdQyYIIosnTMerBO/0Jq1Je1ezmnktzVSFlXeA2cOKEIw=='
    clientSecret: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAHMTVc0y0zg9CkheEQ8djrSAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC1Zmq4pEPAyLkqhXwIBEIBbD9zgW5/+k21v/MOylELL/ylZJ5kQXXXP93pMoEh+ny1VdFoy3ZVBoZ+Y3NdRpCTpmufdXaqPKL5SFKtHUQqjDGx4w0Fy5v0y9WtTOAWyNEgSO42AzEv36ZHj0g=='

aesKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAEknn8joGV1dY2c7x06fJNtAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3vvHm+h6yaalSEDRAgEQgChxNI9aqNevUh4YuQ7Q2MSL6GwQe9fExI/BqUn6yzjXmuNq16vDe8nC'

apiKeys: 0844c776530ac4da07fdbbe3e588ee642a13657e, 799173c1bdcc5b19b2a7a9eccd65178f5673af8e, 2279779a6ffd50f5e8784c2307224fac0d7a9325, 3b252846658f89dd61156c921d18df649938f041, 92574542d968c136c9b3b7bc4502766ba831dc11, da139ba972eee32e734103b4bf7561787fff930e, 6826be840dd21691d06f91a803e93ae7c8722390

# email config
ses:
  sender: support@karroslab.com
  accessKey: AKIARNCTWFL5EMO5CKPN
  secretKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAHTybxOBDaAECabZ47LQ925AAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCbwtUEk8z3S/hhHJwIBEIBDPd1pJdKdRka8WH51X6Qnd/tiPPtd0E3zqJquVegHoMh/TJjNvSIUqlk7bwjKeZAZ1nZt3gzcvdn3HNHSR5fJD1lqsg=='
  region: us-east-1