eureka:
  instances: http://eureka01-p01-stage.usw2.karrostech.net:1112/eureka/,http://eureka02-p01-stage.usw2.karrostech.net:1112/eureka/
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
    healthcheck:
      enabled: true

kafka-list-servers: 10.40.26.222:9092,10.40.26.210:9092,10.40.26.181:9092,10.40.26.75:9092,10.40.26.99:9092
kafka-broker: ${kafka-list-servers} #use in other services, will be remove soon
kafka:
  servers: ${kafka-list-servers} #don't use until all dependent services are correctly configured. ##use in other services, will be remove soon
  bootstrap-server: ${kafka-list-servers}
  athena-bootstrap-msk: b-1.athenamsk.eg7z0i.c3.kafka.us-east-2.amazonaws.com:9092, b-2.athenamsk.eg7z0i.c3.kafka.us-east-2.amazonaws.com:9092

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

elasticSearch:
  logAggregation:
    url: 2ccf0579872b4a3aad8aeda90137dfd6.us-east-1.aws.found.io
    username: elastic
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGcaZWtA+fj+eRZQ7T7FMW+AAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAt4chiKot4qvp5lGAgEQgDMXt7mSjzH4tyl1w4IVqfSuZky+IjABks9nHqTb/H6Umc6PHXYiCpCslksWG4gpIFtxG98='
    port: 9243
  cloud:
    url: e20f6fed69ae415483d527d15665f843.us-west-2.aws.found.io
    username: elastic
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAFcz2hGlo1whipMvvG/T3ktAAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2cOn10HqphJqxN7gAgEQgDP7aE5yQWULCAhcx4C9/yYe86Amdu3qzdxCkdCJQ+NQK/s4DUr8mQZ9OiSB5Jc5cXO9/Ok='
    port: 9243
  aws:
    url: vpc-p01usw2stage-k7cgmx4es77qsmxter5xwj7vnm.us-west-2.es.amazonaws.com
    username:
    password:
    port: 443
  awsv7:
    url: vpc-p01usw2stage-v7-fgczvvgqf5h7zwmoicajtnblua.us-west-2.es.amazonaws.com
    username:
    password:
    port: 443

spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${kafka-list-servers}
    
rds:
  dataSource:
    url: jdbc:postgresql://db-stage.usw2.karrostech.net:5432/Edulog #use in other services, will be remove soon
    username: karros_prod_admin #use in other services, will be remove soon
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGrx/wBTNFYFkMyWMs1zDiRAAAAezB5BgkqhkiG9w0BBwagbDBqAgEAMGUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbdsrRTlU6ozJEvsdAgEQgDjNLewA1V49MQQWNmqjsLYRDmsx+9K7TTNCaePFZ+qDLp0KS/Ock1Cvgg/T6hDEPBCdJqYByDDDnw==' #use in other services, will be remove soon

#DB information
edulog:
  datasource:
    url: jdbc:postgresql://db-stage.usw2.karrostech.net:5432/Edulog
    username: karros_prod_admin
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGrx/wBTNFYFkMyWMs1zDiRAAAAezB5BgkqhkiG9w0BBwagbDBqAgEAMGUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbdsrRTlU6ozJEvsdAgEQgDjNLewA1V49MQQWNmqjsLYRDmsx+9K7TTNCaePFZ+qDLp0KS/Ock1Cvgg/T6hDEPBCdJqYByDDDnw=='
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 10
      max-active: 50
      test-on-borrow: true

# DB Configs
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: master_data
        hbm2ddl:
          import_files:

security:
  jwt:
    issuer: http://karrostech.com #use in other services, will be remove soon
    signature: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsh0GXHEy3S3jOX9QXXT8yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDWTMtLq5qBNuvpYAgEQgDvEFsvknk7vamQJiB5wJmwbF570MckoCVEqD8O7MVwpzzbK8pdXJ4dMDfFUeMcWL+eE/SaCae9u6QX4cQ==' #use in other services, will be remove soon
    duration: # minutes #use in other services, will be remove soon
      token: 120 #use in other services, will be remove soon
      refreshToken: 60 #use in other services, will be remove soon

    tokenExpirationTime: 120 # Number of minutes
    refreshTokenExpTime: 60 # Minutes
    tokenIssuer: http://karrostech.com 
    # base 64 encoded signing key
    tokenSigningKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsh0GXHEy3S3jOX9QXXT8yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDWTMtLq5qBNuvpYAgEQgDvEFsvknk7vamQJiB5wJmwbF570MckoCVEqD8O7MVwpzzbK8pdXJ4dMDfFUeMcWL+eE/SaCae9u6QX4cQ=='
    secureAuthenticationEntryUrl: /api/**/students/**
    unsecurePathList: [/v2/api-docs/**, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /swagger-ui.html/**, /webjars/**, /swagger-resources/configuration/ui,
                     /swagger-resources/configuration/security, /manage/**, /api/v1/people ]
    enableKeycloakJWT: true
    keycloakTokenIssuer: karros-keycloak
    keycloakPublicKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAG18ENckimRuswVgz0Sr8YxAAAB8DCCAewGCSqGSIb3DQEHBqCCAd0wggHZAgEAMIIB0gYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwUWRoqPyToO3UeL5YCARCAggGja64FJpPl9+NuG5SvCnDoady0f3grc49KG6xQDUXIfMPqLHFK/1AGsnWfup2vcLMhwu1NOWtL84Y11LSIGe3EPSJhLdIW5wPTVtV37j3bAc5WShPxkL9VFJQwDHeCqx5ijeUz7cAb25txuvqdz2BT/5zpdnwo4hteYi9j/72VvLE1GFApFDC2mZYruyAo47WtvNR4hfco+Um0vs6vDreMgPlmjXHBPW4ErM+2I0fMsD64lVH7NUEMn+3AmcIPxYvCLNdDHMWGb3zrNtf7xdQsG1efxWHSO3Vib4MzgYVHOJCBKUpnWBeRsBoOFYIPxs419dx9rSr/DIlRUGvDQHouQbUXCAvnlqxgE89bpUqaj5vjk2nB4mISf2IkymNNV1lVuErRR+iA1A5rK2+QIB/H4Okuo5nB01gdLm3eodZBI6KzblDbOSMxKbKdKbJurdi1QRYv1GT/QpSWJ1zXD7jcJaQKDcW9C9s3e4oa/70g14/ODkxxhabeim+x2bZOUQmmP91OKmW/N9pdq6ld/Escp11+WAaeIddwI4ih1G+KpPcd/pA='

auth:
  credentials:
    clientId: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGmPuYgvi3Lf7P5TWnsf8JfAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJMYu4jRoIBsa6XbCQIBEIBD/A+aT/5ePQslezNxhmUdvJtoI+/BJDMfdOTqMzcyZKu4GPWTgG1ZWkXw1vlvk5dFz9Gx/xZRG8mfJuA3zM7kbzxECw=='
    clientSecret: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAHb0IfPLp/eDFvfIcl5LQTSAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDH4LBpJloA6W7YSLvwIBEIBbdqhIaNfX+NYqo5yckaU4vbeIjqt2haLWRDRejhl1XKZUTKXVBUonsrmw+NRl41HeDNLeLu3BLh8Rs/+TArRr9m01n7zHDwTQsn2TiNdLW2wSdVWWqSawrXad8Q=='

aesKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAEknn8joGV1dY2c7x06fJNtAAAAazBpBgkqhkiG9w0BBwagXDBaAgEAMFUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3vvHm+h6yaalSEDRAgEQgChxNI9aqNevUh4YuQ7Q2MSL6GwQe9fExI/BqUn6yzjXmuNq16vDe8nC'

apiKeys: 11bb4c1845c7a0137ad0bc8f1df055792849df16, c62ac14ec31ffdd04d98268aeb6ec3b5244b1bcf, 94d9b8d2c7433f7145ae5d83bf2a73310b6c0628, 9d6c3f85669a40cd1b1fa4635b049b92bb04c881, f84f6e88351fbf27f2c58643063b84d263318ae2, 7573c26b16993ef536dc9397f5c08911a551c79a, dda54ae0a6b57658537d01ac47deca8799c965ca

# email config
ses:
  sender: support@karroslab.com
  accessKey: AKIARNCTWFL5EMO5CKPN
  secretKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAHTybxOBDaAECabZ47LQ925AAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCbwtUEk8z3S/hhHJwIBEIBDPd1pJdKdRka8WH51X6Qnd/tiPPtd0E3zqJquVegHoMh/TJjNvSIUqlk7bwjKeZAZ1nZt3gzcvdn3HNHSR5fJD1lqsg=='
  region: us-east-1