ribbon.eureka.enabled: false 
eureka.client.enabled: false

spring.redis.host: redis.use2.karrostech.net
spring.redis.port: 6379
spring.redis.database: 4
spring.redis.password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAFFhusdkXy9d+V+BwBDdmcEAAAAfDB6BgkqhkiG9w0BBwagbTBrAgEAMGYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvTSoZuC9earPV34BAgEQgDmE8Qs8TG/JZFPWdVPxs94sP15ZhbJT1j8XUvev3x7IMoB8KTSivPp6uHn4HoR4uB7RPBwFKaiPvtU='

spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 1
spring.redis.jedis.pool.max-idle: 8

qrCode:
  cipherKey: QaE7ZLruDCNe7AhH
  expirationTimeInMonth: 1

es:
  url: ${elasticSearch.systemManagement.url}
  username: ${elasticSearch.systemManagement.username}
  password: ${elasticSearch.systemManagement.password}
  port: ${elasticSearch.systemManagement.port}
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  maxSizeQuery: 10000
  indices:
    proposedStudentDelete:
      index: proposed_student_delete
      type: doc
    proposedRouteDelete:
      index: proposed_route_delete
      type: doc
  parallelESCountThreads: 100

kafka:
  consumer:
    proposedStudentDeletes: proposedStudentDeletes-p01use2dev
  producer:
    publishNotificationRequestTopic: publishNotificationRequest-p01use2dev
  consumer-group: systemmanagementwsapi-consumer-group-p01use2dev
  applicationId: systemmanagementWSAPI-dev

batchProcessor:
  batchSizePublishEvent: 500