# Property file for demo use. Will be used if spring.profiles.active is set to demo
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: true

kafka:
  bootstrap: ${kafka-list-servers}
  groupId: testchangedStudentTripGroup
  producer:
    topic: changedStudentTrip-p01usw2demo

# DB Configs
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: karrosingestion
        hbm2ddl:
          import_files:

edulog:
  datasource:
    url: jdbc:postgresql://db-demo.usw2.karrostech.net:5432/Edulog
    username: karros_demo_admin
    password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGAZqedu7TExJSmFH1p7+z6AAAAejB4BgkqhkiG9w0BBwagazBpAgEAMGQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMy66nGIYPRS13pBG4AgEQgDeo559ch4bpvNdvIeZDhRxTc7iF6dJyM+fyUWw4pL6dH69vQlqPV1RgRyz2bZF/3ILPPQrxdjmP'
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 10
      max-active: 100
      test-on-borrow: true

# Spring Security configurations
security.jwt:
  tokenExpirationTime: ${security.jwt.duration.token} # Number of minutes
  refreshTokenExpTime: ${security.jwt.duration.refreshToken} # Minutes
  tokenIssuer: ${security.jwt.issuer}
  # base 64 encoded signing key
  tokenSigningKey: ${security.jwt.signature}
  secureAuthenticationEntryUrl: /api/**
  unsecurePathList: [/v2/api-docs/**, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /swagger-ui.html/**, /webjars/**, /swagger-resources/configuration/ui,
                     /swagger-resources/configuration/security, /manage/** ]
  applications: ["ParentPortal", "*", "Insight", "TenantManagement"]
security.basic.enabled: false
management.security.enabled: false

credentials:
  ApiKey: ${auth.credentials.clientId}
  clientSecret: ${auth.credentials.clientSecret}

microservices:
  authenticationService:
    serviceId: AUTHSERVICE
    get-credentials:
      endpoint: http://${microservices.authenticationService.serviceId}/api/v1/signin
