# Property file for DevTest tier. Will be used if spring.profiles.active is set to "staging"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

# ES7 config
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10
  indexes:
    transportationrequest: transportation_request
    rideregistration: transportation_request_v3

kafka:
  bootstrap-msk: ${kafka.athena-bootstrap-msk}
  consumer:
    changedStudentPerson: changedStudentPerson-p01usw2demo
    schoolChange: schoolChange-p01usw2demo
    transportationRequestChange: athenaTransportationRequestChange-p01usw2demo
  consumer-group: transportationRequestWSAPI-p01usw2demo
  applicationId: transportationRequestWSAPI-p01usw2demo
  producer:
    rideRegistrationChange: rideRegistrationChange-p01usw2demo