kafka:
  bootstrap-server: ${kafka-broker}
  consumer-group: inventoryService-default
  producer:
    equipmentTopic: equipment-info-p01usw2dev
spring:
  cloud:
    stream:
      kafka:
        streams:
          bindings:
            equipmentInputBinding:
              consumer:
                applicationId: inventoryService-default
                startOffset: latest
          binder:
            brokers: ${kafka-broker}
            applicationId: inventoryService-default
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
              commit.interval.ms: 1000
      bindings:
        equipmentInputBinding:
          destination: vehicle-info-default
          group: inventoryService-default
          binder: kafka3
      binders:
        kafka3:
          type: kstream
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        ddl-auto: none
        default_schema: public
        use_jdbc_metadata_defaults: false
        hbm2ddl:
          import_files:

edulog:
  datasource:
    # fix test env, please update again
    url: jdbc:h2:mem:Edulog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;INIT=create schema IF NOT EXISTS public
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    test-while-idle: true
    validation-query: select 1
    tomcat:
      max-wait: 10000
      initialSize: 1
      max-active: 5
      test-on-borrow: true
    dev:
      url: jdbc:h2:mem:Edulog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;INIT=create schema IF NOT EXISTS public
      username: sa
      password: sa
      driverClassName: org.h2.Driver
      test-while-idle: true
      validation-query: select 1
      tomcat:
        max-wait: 10000
        initialSize: 1
        max-active: 5
        test-on-borrow: true
