kafka:
  bootstrap-server: ${kafka-broker}
  consumer-group: inventoryService-p01usw1prod
  producer:
    equipmentTopic: equipment-info-p01usw1prod
spring:
  cloud:
    stream:
      kafka:
        streams:
          bindings:
            equipmentInputBinding:
              consumer:
                applicationId: inventoryService-p01usw1prod
                startOffset: latest
          binder:
            brokers: ${kafka-broker}
            applicationId: inventoryService-p01usw1prod
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
              commit.interval.ms: 1000
      bindings:
        equipmentInputBinding:
          destination: vehicle-info-p01usw1prod
          group: inventoryService-p01usw1prod
          binder: kafka3
      binders:
        kafka3:
          type: kstream
  jpa:
    properties:
      hibernate:
        default_schema: public