spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: master_data
        hbm2ddl:
          import_files:
        format_sql: true

edulog:
  datasource:
    url: jdbc:postgresql://db-demo.usw2.karrostech.net:5432/Edulog
    username: karros_demo_admin
    password: c0mb1nat10nTrunkC0mp0undC00k
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      max-idle: 50
      test-on-borrow: false

es:
  url: 8c86d819876e464dbbb6823dbf2f49c6.us-west-2.aws.found.io
  username: elastic
  password: PMFuUgkRh8bIAJU4wro3qYX6
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 9243
  query:
    detectRadius: 10m
    maxHitThreshold: 30
    eventSearchWindow: 10m
