
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

eureka.client.healthcheck.enabled: true
ribbon.eureka.enabled: false

spring.redis.host: redis.use2.karrostech.net
spring.redis.port: 6379
spring.redis.password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAFygaQGqTM9+fOupFyJyoS2AAAAfDB6BgkqhkiG9w0BBwagbTBrAgEAMGYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOyFWHmeGDfK9FKYFAgEQgDld2OogLrbzrKBA3GuW7M5PefamTGHGqKCOsXFCTAPqYvWw4d3FF2jl/1+arIwMaBpExwLSvzIiTBI='

spring.redis.jedis.pool.max-active: 30
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 10
spring.redis.jedis.pool.max-idle: 30

# Custom redis factory
spring.redis.accessrequest.host: ${spring.redis.host}
spring.redis.accessrequest.port: ${spring.redis.port}
spring.redis.accessrequest.database: 0
spring.redis.accessrequest.password: ${spring.redis.password}

spring.redis.vehicle.host: ${spring.redis.host}
spring.redis.vehicle.port: ${spring.redis.port}
spring.redis.vehicle.database: 4
spring.redis.vehicle.password: ${spring.redis.password}
# Custom redis factory

es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10
  index:
    name: scanhistories-*

buffered-es-bulk-index:
  batch-size: 500
  retention-ms: 1000
  buffer-size: 5000

kafka-processors:
  enabled: false