# Property file for DevTest tier. Will be used if spring.profiles.active is set to "test"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-prod.usw1.karrostech.net:1112/eureka/

index: realtimevehiclesevents*
type: doc
ElasticSearchURL: vpc-p01usw1prod-mk5xmhey72i44thke3onjjacda.us-west-1.es.amazonaws.com
usernamee:
password:
port: 443

spring.redis.host: redis-prod.usw1.karrostech.net
spring.redis.port: 6379
spring.redis.database: 4
spring.redis.password:

# For old version
spring.redis.pool.max-active: 30
spring.redis.pool.max-wait: 5000
spring.redis.pool.min-idle: 10
spring.redis.pool.max-idle: 30