eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false

management:
  health:
    redis:
      enabled: false

# For debugging, disable token verification
disableValidateToken: true

# API Keys that are acceptable
validApiKeys: ${apiKeys}

audit:
  loggedBy: ${spring.application.name}
  enabled: false
  methods: POST,PUT,DELETE,PATCH, GET
  defaultIgnoredEndpoints:
  defaultStoreResponseBody: true
  defaultStoreRequestBody: true
  #This header will be added before Zuul routing, but Zuul auto converts to lower case, so the value should be in lower case
  xTrkHeaderKeyName: x-trk-id
  customRequests:
    -
      endpoints: /api/v1/vehicleStatus, /api/0.2/events/vehicleId?vehicleId=
      methods: GET
      enabled: false
      storeRequestBody: true
      storeResponseBody: false
    -
      endpoints: /search, /bulksearch, /export
      methods: POST, GET
      enabled: true
      storeRequestBody: true
      storeResponseBody: false

customForwarding:
  urlRewrites:
    -
      sourcePath: /api/v1/pp/vehicleliveevents/search(.)*
      targetPath: /api/v1.0/vehicleliveevents/search
      targetServiceId: VEHICLELIVEEVENTSERVICE
    -
      sourcePath: /api/v2/subscriptions/alertzones
      targetPath: /api/v1/geofences
      targetServiceId: GEOFENCEALERTMANAGEMENTSERVICE
    -
      sourcePath: /api/v2/subscriptions/alertzones/search
      targetPath: /api/v1/geofences/search
      targetServiceId: GEOFENCEALERTMANAGEMENTSERVICE
    -
      sourcePath: /api/v2/subscriptions/alertzones/([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})
      targetPath: /api/v1/geofences/%s
      targetServiceId: GEOFENCEALERTMANAGEMENTSERVICE

caching:
  enabled: false
  defaultCaching: NONE
  defaultTTL: 10000
  defaultIgnoredEndpoints: /export, /download
  customCaching:
    -
      apis: POST|/api/v2/subscriptions/alertzones/search
      enabled: true
      ttl: 10000

spring.redis.host: redis.use2.karrostech.net
spring.redis.port: 6379
spring.redis.database: 4
spring.redis.password: B8VZKjs4LL8a24Gq7zftw2M4eQvNmQ

spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 1
spring.redis.jedis.pool.max-idle: 8

zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  ribbonIsolationStrategy: THREAD
  routes:
    inventoryService:
      path: /api/*/equipment/**
      serviceId: INVENTORYSERVICE
      stripPrefix: false
    athenaETLService:
      path: /api/*/athenaetl/**
      serviceId: ATHENAETLSERVICE
      stripPrefix: false
  retryable: true