# Property file for local use. Will be used if spring.profiles.active = demo

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: true

ribbon:
  eureka:
    enabled: true

spring:
  redis:
    port: 6379
    host: redis-demo.usw2.karrostech.net
    database: 0
    password: J4r8qXA44w6ZukWAtR6qU7wJcKvXTA
default.notification.disable: false
kafka: 
  applicationId: studenttripChangesNotifier-p01use2demo
  consumer-group: studenttripChangesNotifier-p01use2demo
  consumer:
    studentTripChanges: changeStudentTrip-p01usw2demo_v2
  producer:
    publishNotificationRequest: publishNotificationRequest-p01usw2demo

