# Property file for local use. Will be used if spring.profiles.active = demo

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: true

ribbon:
  eureka:
    enabled: true
default.notification.disable: false

kafka: 
  applicationId: studenttripChangesNotifier-p01use2demo
  consumer-group: studenttripChangesNotifier-p01use2demo
  consumer:
    studentTripChanges: changeStudentTrip-p01usw2demo_v2
  producer:
    publishNotificationRequest: publishNotificationRequest-p01usw2demo

