# Property file for local use. Will be used if spring.profiles.active = dev

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: true

ribbon.eureka.enabled: false
    
spring:
  redis:
    port: 6379
    host: redis-stage.usw2.karrostech.net
    database: 0
    password: MwMNehjHjN9Yta63xQq6gEcAQJ8h5G

default.notification.disable: false

kafka: 
  applicationId: studenttripChangesNotifier-p01use2stage
  consumer-group: studenttripChangesNotifier-p01use2stage
  consumer:
    studentTripChanges: changeStudentTrip-p01usw2stage_v2
  producer:
    publishNotificationRequest: publishNotificationRequest-p01usw2stage

