eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  consumer:
    group-id: rideRegistrationChange-usw1prod
  topic:
    ride-registration-change: rideRegistrationChange-p01usw1prod
    msk-suffix:
      ride-registration-change: athenaRideRegistrationChange-usw1prod