eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false
eureka.client.enabled: false

kafka:
  consumer:
    group-id: rideRegistrationChange-usw2stage
  topic:
    ride-registration-change: rideRegistrationChange-p01usw2stage
    msk-suffix:
      ride-registration-change: athenaRideRegistrationChange-usw2stage