# Property file for DevTest tier. Will be used if spring.profiles.active is set to "staging"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  consumer-group: rideRegistrationChange-kafka-consumer-group-usw2demo
  topic:
    ride-registration-change: rideRegistrationChange-p01usw2demo
    msk-suffix:
      ride-registration-change: rideRegistrationChange-usw2demo