eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  consumer:
    group-id: rideRegistrationChange-usw2test
  topic:
    ride-registration-change: rideRegistrationChange-p01usw2test
    msk-suffix:
      ride-registration-change: athenaRideRegistrationChange-usw2test