eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  consumer:
    group-id: rideRegistrationChange-usw2demo
  topic:
    ride-registration-change: rideRegistrationChange-p01usw2demo
    msk-suffix:
      ride-registration-change: athenaRideRegistrationChange-usw2demo