eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  consumer:
    group-id: rideRegistrationChange-use2dev
  topic:
    ride-registration-change: rideRegistrationChange-p01use2dev
    msk-suffix:
      ride-registration-change: athenaRideRegistrationChange-use2dev