# Property file for DevTest tier. Will be used if spring.profiles.active is set to "staging"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false
eureka.client.enabled: false

kafka:
  consumer-group: rideRegistrationChange-kafka-consumer-group-usw2stage
  topic:
    ride-registration-change: rideRegistrationChange-p01usw2stage
    msk-suffix:
      ride-registration-change: rideRegistrationChange-usw2stage