eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

es:
  url: 8c86d819876e464dbbb6823dbf2f49c6.us-west-2.aws.found.io
  username: elastic
  password: PMFuUgkRh8bIAJU4wro3qYX6
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 9243
  query:
    detectRadius: 10m
    maxHitThreshold: 30
    eventSearchWindow: 10m

management:
  endpoint:
    info:
      enabled: true

management.health.elasticsearch.enabled: false
management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.defaults.enabled: true    
