
kafka:
  bootstrap-msk: ${kafka.athena-bootstrap-msk}
  applicationId: athenaETLService
  consumer-group: athenaETLService-p01use2dev
  consumer:
    athenaSchoolChange: athenaSchoolChange-p01use2dev
    athenaStudentChange: athenaStudentChange-p01use2dev
    
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10 
------------


kafka:
  bootstrap-msk: ${kafka.athena-bootstrap-msk}
  applicationId: athenaETLService
  consumer-group: athenaETLService-p01use2dev
  consumer:
    athenaSchoolChange: athenaSchoolChange-p01use2dev
    athenaStudentChange: athenaStudentChange-p01use2dev
    
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10 

kafka:
  bootstrap-msk: ${kafka.athena-bootstrap-msk}
  applicationId: athenaETLService
  consumer-group: athenaETLService-p01use2dev
  consumer:
    athenaSchoolChange: athenaSchoolChange-p01use2dev
    athenaStudentChange: athenaStudentChange-p01use2dev
    
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10 
