# Property file for local use. Will be used if spring.profiles.active is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.elasticsearch.enabled: false

#Accepted status values
validStatusTypes: "Active, Revoked"
connectionTimeout: 10000
socketTimeout: 60000
maxScrollSize: 10000
defaultTimeOutinSec: 120
registrationCodeLength: 8

index: alertzones
type: doc
parallelESCountThreads: 250

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.apache.kafka: INFO

kafka-broker: 10.20.20.121:9092
spring.cloud.stream.bindings:
  inputDD:
    destination: run-sub-es-results
    #binder: kafkaddinput
  outputDD:
    destination: run-sub-dd-ktable
    #binder: kafkaddoutput
  inputRA:
    destination: run-sub-ra-results
    #binder: kafkarainput
  outputRA:
    destination: run-sub-ra-ktable
    #binder: kafkaraoutput
  inputRO:
    destination: run-sub-ro-results
    #binder: kafkarainput
  outputRO:
    destination: run-sub-ro-ktable
  ddTable:
    destination: run-sub-dd-ktable
  roTable:
    destination: run-sub-ro-ktable
  raTable:
    destination: run-sub-ra-ktable
  inputRaWithRoKtable:
    destination: ra-ro-ktable
  outputRaWithRoKtable:
    destination: ra-ro-ktable
  outputJoinedResults:
    destination: run-agg-results

    #binder: kafkaraoutput
spring.cloud.stream.kafka.streams.bindings:
  inputDD:
    consumer:
      applicationId: run-substitution-aggregate-service-dd
  inputRA:
    consumer:
      applicationId: run-substitution-aggregate-service-ra
  inputRO:
    consumer:
      applicationId: run-substitution-aggregate-service-ro
  ddTable:
    consumer:
      applicationId: run-substitution-aggregate-service-ddKtable
  raTable:
    consumer:
      materializedAs: routeAssignmentsStore
      applicationId: run-substitution-aggregate-service-raKtable
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
  roTable:
    consumer:
      applicationId: run-substitution-aggregate-service-roKtable
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
  inputRaWithRoKtable:
    consumer:
      applicationId: ra-with-ro-joined-ktable
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde

spring.cloud.stream.kafka.bindings.inputRA.consumer:
  autoCommitOnError: true
spring.cloud.stream.kafka.bindings.inputRO.consumer:
  autoCommitOnError: true
spring.cloud.stream.kafka.bindings.inputDD.consumer:
  autoCommitOnError: true

spring.cloud.stream.kafka.streams:
  binder:
    brokers: 10.20.20.121:9092
    applicationId: run-substitution-aggregate-service-dev
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit.interval.ms: 1000
      auto.offset.reset: earliest
maxNumberOfMessages: 20
current-version:
  version: version1
  config:
    coefficient-dd: 1
    coefficient-ro: 1
    coefficient-ra: 1
raScore: 1
raStore: routeAssignmentsStore