# Property file for local use. Will be used if spring.profiles.active is not set


# Worker configs
kafka_broker: 10.40.26.222:9092
schema_registry_broker: 10.40.26.222:8081

worker_key_converter: org.apache.kafka.connect.storage.StringConverter
worker_value_converter: io.confluent.connect.avro.AvroConverter
offset_storage_file: /tmp/connect.offsets
plugin_path: "share/java,share/confluent-hub-components"
consumer_max_poll_interval_ms: 30000

# Connector configs

connector_class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks_max: 1
connecttopic: route-assignment-p01usw2demo
elasticsearch_url: https://8c86d819876e464dbbb6823dbf2f49c6.us-west-2.aws.found.io:9243
es_username: kafka-connect
es_password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAG368a8i4x8+iCUm3cw/ooMAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpLavzK9d/lZS5G7MAgEQgCuPoTwmiRflBz3pyKl9fSDnR+373taYI3rmdHMlJx0QTyXTqQHcSl6o8+ev'
index: routeassignmenthistory-
key_ignore: true
schema_ignore: false
type_name: _doc
connector_key_converter: org.apache.kafka.connect.storage.StringConverter
connector_value_converter: io.confluent.connect.avro.AvroConverter
connector_key_converter_schema_enabled: true
connector_value_converter_schema_enabled: true
connector_internal_key_converter_schema_enabled: true
connector_internal_value_converter_schema_enabled: true
connector_internal_key_converter: org.apache.kafka.connect.storage.StringConverter
connector_internal_value_converter: org.apache.kafka.connect.json.JsonConverter
connector_error_tolerance: none
