eureka:
  hostname: ${eureka.instances}
  service_port: 8100

auth:
  clientId: ${auth.credentials.clientId}
  clientSecret: ${auth.credentials.clientSecret}
  grantType: client_credentials
  scope: Parent Portal

app_config:
  name: EsqlFetchSource
  fetch_retry_count: 10
  thread_count: 10
  log_level: "DEBUG"
  key: ${aesKey}
  bad_char: "[1, 2, 3]"

elastic_search:
  url: ${elasticSearch.aws.url}
  port: ${elasticSearch.aws.port}
  password: ${elasticSearch.aws.password}
  username: ${elasticSearch.aws.username}
  timeout: 5s
  result_index: esqlimportresult
  route_index: esqlroute
  student_index: esqlstudent
  driver_directions_index: esql.driver.directions

gateway:
  url: https://gateway-p01-stage.usw2.karrostech.net

kafka:
  bootstrap: ${kafka.servers}
  nifi_topic: esqlFetchStatus-p01usw2stage
  student_delete: proposedStudentDeletes-p01usw2stage
  route_delete: proposedRouteDeletes-p01usw2stage
  retries: 5
  
