eureka:
  hostname: ${eureka.instances}
  service_port: 8100

auth:
  clientId: ${auth.credentials.clientId}
  clientSecret: ${auth.credentials.clientSecret}
  grantType: client_credentials
  scope: Parent Portal

app_config:
  name: EsqlFetchSource
  fetch_retry_count: 10
  thread_count: 10
  log_level: "DEBUG"
  key: ${aesKey}
  bad_char: "[1, 2, 3]"

elastic_search:
  url: ${elasticSearch.cloud.url}
  port: ${elasticSearch.cloud.port}
  password: ${elasticSearch.cloud.password}
  username: ${elasticSearch.cloud.username}
  timeout: 8m
  result_index: esqlimportresult
  route_index: esqlroute
  student_index: esqlstudent
  driver_directions_index: esql.driver.directions

gateway:
  url: https://gateway-p03-prod.usw1.karrostech.net

kafka:
  bootstrap: ${kafka-broker}
  topic: esqlFetchStatus-p01usw1prod
  nifi_topic: esqlFetchStatus-p01usw1prod
  student_delete: proposedStudentDeletes-p01usw1prod
  route_delete: proposedRouteDeletes-p01usw1prod
  retries: 5
