# Property file for local use. Will be used if spring.profiles.active is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}


endpoints.sensitive: true
management.security.enabled: false
management.context-path: /

maxVehicleLimit: 5
kafka:
  bootstrap: ${kafka-list-servers}
  consumer-group: vehicleManagementService-p01usw1prod
  tenant:
    groupId: tenantConsumer-vms-prod
    topic: tenantChanged-p01usw1prod
  equipment:
    topic: equipment-info-p01usw1prod
vehicletopic: vehicle-info-p01usw1prod
vehicleversion: 1.0
equipmenttopic: equipment-info-p01usw1prod
equipmentversion: 1.0
availabilitytopic: availability-info-p01usw1prod
availabilityversion: 1.0
depottopic: depot-info-p01usw1prod
depotversion: 1.0


# DB Configs
spring:
  redis:
    host: redis-prod.usw1.karrostech.net
    port: 6379
    database: 0
    password: 
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: vms
        hbm2ddl:
          import_files:
        format_sql: true

  
edulog:
  datasource:
    url: ${rds.dataSource.url}
    username: ${rds.dataSource.username}
    password: ${rds.dataSource.password}
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      max-idle: 50
      test-on-borrow: false
assignment.env: prod
