# Property file for local use. Will be used if spring.profiles.active is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false

endpoints.sensitive: true
management.security.enabled: false
management.context-path: /

maxVehicleLimit: 5
kafka:
  bootstrap: ${kafka-list-servers}
  consumer-group: vehicleManagementService-p01usw2stage
  tenant:
    groupId: tenantConsumer-vms-stage
    topic: tenantChanged-p01usw2stage
  equipment:
    topic: equipment-info-p01usw2stage
vehicletopic: vehicle-info-p01usw2stage
vehicleversion: 1.0
equipmenttopic: equipment-info-p01usw2stage
equipmentversion: 1.0
availabilitytopic: availability-info-p01usw2stage
availabilityversion: 1.0
depottopic: depot-info-p01usw2stage
depotversion: 1.0
# DB Configs
spring:
  redis:
    port: 6379
    host: redis-stage.usw2.karrostech.net
    database: 0
    password: MwMNehjHjN9Yta63xQq6gEcAQJ8h5G
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: vms
        hbm2ddl:
          import_files:
        format_sql: true

  
edulog:
  datasource:
    url: ${rds.dataSource.url}
    username: ${rds.dataSource.username}
    password: ${rds.dataSource.password}
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      max-idle: 50
      test-on-borrow: false
assignment.env: stage
defaultcapacitymapping: '[{"seatingTypeCode":"GE","seatingType":"General Education","capacity":50,"isDefault":true},{"seatingTypeCode":"WC","seatingType":"Wheel Chair","capacity":5,"isDefault":true},{"seatingTypeCode":"HAR","seatingType":"Harness","capacity":6,"isDefault":true},{"seatingTypeCode":"CS","seatingType":"Car seat","capacity":6,"isDefault":true},{"seatingTypeCode":"PAR","seatingType":"Paraplegic","capacity":6,"isDefault":true}]'