eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false

management:
  health:
    redis:
      enabled: false

# API Keys that are acceptable
validApiKeys: ${apiKeys}
whiteListedRequest: /signin, /signup, /forgotpassword, /verificationemail, /resetpassword, /sendverificationemail, /verified, /v2/api-docs

zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  ribbonIsolationStrategy: THREAD
  routes:
    telematicsSubscriptionService:
      path: /api/*/telematics/**
      serviceId: TELEMATICSSUBSCRIPTIONSERVICE
      stripPrefix: false
    vehiclemanagementservice: 
      path: /vehiclemanagementservice/**
      serviceId: VEHICLEMANAGEMENTSERVICE
      stripPrefix: true
    vehiclemanagementservice_graphql: 
      path: /vms/**
      serviceId: VEHICLEMANAGEMENTSERVICE
      stripPrefix: true
    routeVehicleAssignmentService:
      path: /api/*/rovars/**
      serviceId: ROUTEVEHICLEASSIGNMENTSERVICE
      stripPrefix: false
    athenawsapi:
      path: /api/*/athena/**
      serviceId: ATHENAWSAPI
      stripPrefix: false
    historicalProcessedEvent:
      path: /api/*/fetchHistoricalProcessedEvents/**
      serviceId: HISTORICALPROCESSEDEVENTSSERVICE
      stripPrefix: false
  retryable: true
audit:
  loggedBy: ${spring.application.name}
  enabled: true
  methods: POST,PUT,DELETE,PATCH, GET
  defaultIgnoredEndpoints:
  defaultStoreResponseBody: true
  defaultStoreRequestBody: true
  #This header will be added before Zuul routing, but Zuul auto converts to lower case, so the value should be in lower case
  xTrkHeaderKeyName: x-trk-id
  customRequests:
    -
      endpoints: /api/v1/vehicleStatus, /api/0.2/events/vehicleId?vehicleId=
      methods: GET
      enabled: false
      storeRequestBody: true
      storeResponseBody: false
    -
      endpoints: /search, /bulksearch, /export
      methods: POST, GET
      enabled: true
      storeRequestBody: true
      storeResponseBody: false
