management.health.elasticsearch.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-prod.usw1.karrostech.net:1112/eureka/

kafka:
  bootstrap-server: ${kafka-list-servers}
  runSubstitution:
    topicName: run-agg-results-p01usw1prod-
  routeOverride:
    topicName: run-sub-ro-results-p01usw1prod
  assignmentChangeRequest:
    topicName: assignmentChangeRequest-p01usw1prod
  consumer:
    changeRouteAssignment: changeRouteAssignment-p01usw1prod
    publishNotificationRequest: publishNotificationRequest-p01usw1prod
    runSubstitution: run-agg-results-p01usw1prod
    eventsGroupId: substitutionWSAPI-p01usw1prod
  applicationId: substitutionWSAPI-prod
es:
  url: vpc-substitutionwsapi-prod-3eysw3i3p6ammoyxdiaxkqrwtu.us-west-1.es.amazonaws.com
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  username:
  password:
  port: 443
  runSubstitution:
    index: run_scored_vehicles-*
    type: doc
  subsitutionHistory:
    index: substitution_history-*
    type: doc
  runDetectionInfo:
    index: detectioninfo
    type: doc

# TODO: encrypt these credentials
credentials:
  ApiKey: 11bb4c1845c7a0137ad0bc8f1df055792849df16
  clientSecret: feb4747c886c6f96385c918f6a6a73c286d9bb3a2dce19f47d8b83ba566acc35

latest-timerange:
  type: recent
  value: 10

spring:
  redis:
    general:
      host: redis-prod.usw1.karrostech.net
      port: 6379
      database: 0
      password:
      cacheExpirations:
        Paths: -1
        Tenants: -1
        vehicles: -1
        substitution: 86400
        CURRENT_ASSIGNMENTS: 600
    vehicle:
      host: ${spring.redis.general.host}
      port: ${spring.redis.general.port}
      database: 4
      password:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true

buffered-es-bulk-index:
  batch-size: 1000
  retention-ms: 1000
  buffer-size: 50000

maxCombinationRunScoreVehicle: 10000

kafka-processors:
  enabled: false
