# Property file for local use. Will be used if spring.profiles.active is not set


# Worker configs
kafka_broker: 10.40.26.222:9092
schema_registry_broker: 10.40.26.222:8081

worker_key_converter: org.apache.kafka.connect.storage.StringConverter
worker_value_converter: io.confluent.connect.avro.AvroConverter
offset_storage_file: /tmp/connect.offsets
plugin_path: "share/java,share/confluent-hub-components"
consumer_max_poll_interval_ms: 30000


# Connector configs

connector_class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks_max: 1
connecttopic: vehicle-info-p01usw2demo 
elasticsearch_url: https://vpc-p01usw2demo-pgoqcktapacbnxneodwtqaieem.us-west-2.es.amazonaws.com
index: vehiclechangehistory-
key_ignore: true
schema_ignore: true
type_name: _doc
connector_key_converter: org.apache.kafka.connect.storage.StringConverter
connector_value_converter:  org.apache.kafka.connect.json.JsonConverter
connector_key_converter_schema_enabled: true
connector_value_converter_schema_enabled: true
connector_internal_key_converter_schema_enabled: true
connector_internal_value_converter_schema_enabled: true
connector_internal_key_converter: org.apache.kafka.connect.json.JsonConverter
connector_internal_value_converter: org.apache.kafka.connect.json.JsonConverter
connector_error_tolerance: all
