eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-demo.usw2.karrostech.net:1112/eureka/,http://eureka02-p01-demo.usw2.karrostech.net:1112/eureka/

spring.cloud.stream.bindings:
  input:
    destination: aggregateAVLEvents-p01usw2demo
  output:
    destination: run-sub-es-results-p01usw2demo

spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${kafka-list-servers}
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
      commit.interval.ms: 1000
      auto.offset.reset: latest

ElasticSearchURL: vpc-p01usw2demo-pgoqcktapacbnxneodwtqaieem.us-west-2.es.amazonaws.com

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443
  query:
    size: 5
    detectRadius: 10m
