eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-prod.usw1.karrostech.net:1112/eureka/,http://eureka02-p01-prod.usw1.karrostech.net:1112/eureka/

spring.cloud.stream.bindings:
  input:
    destination: aggregateAVLEvents-p01usw1prod
  output:
    destination: run-sub-es-results-p01usw1prod

spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${kafka-list-servers}
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
      commit.interval.ms: 1000
      auto.offset.reset: latest

ElasticSearchURL: vpc-p01usw1prod-mk5xmhey72i44thke3onjjacda.us-west-1.es.amazonaws.com

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443
  query:
    size: 5
    detectRadius: 10m