eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

spring.cloud.stream.bindings:
  input:
    destination: aggregateAVLEvents-p01usw2stage
  output:
    destination: run-sub-es-results-p01usw2stage

spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${kafka-list-servers}
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
      commit.interval.ms: 1000
      auto.offset.reset: latest

ElasticSearchURL: ${elasticSearch.aws.url}

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443
  query:
    size: 5
    detectRadius: 10m
