eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: true

ribbon:
  eureka:
    enabled: true


kafka: 
  applicationId: substitutionNotifier-p01use2demo
  consumer-group: substitutionNotifier-p01use2demo
  consumer:
    changeRouteAssignment: changeRouteAssignment-p01usw2demo
    substitutionNotifier: substitutionNotifierInternalTopic-p01use2demo
  producer:
    substitutionNotifier: substitutionNotifierInternalTopic-p01use2demo
    publishNotificationRequest: publishNotificationRequest-p01usw2demo

es:
  url: ${elasticSearch.aws.url}
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  username:
  password:
  port: 443
  subsitutionHistory:
    index: substitution_history-*
    type: doc

spring:
  redis:
    host: redis-demo.usw2.karrostech.net
    port: 6379
    database: 0
    password: J4r8qXA44w6ZukWAtR6qU7wJcKvXTA
    
      