# Property file for Devtest environment. Will be used if spring.profiles.active isset to test
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      
# DB Configs
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: public
        hbm2ddl:
          import_files:

edulog:
  datasource:
    url: ${rds.dataSource.url}
    username: ${rds.dataSource.username}
    password: ${rds.dataSource.password}
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 20
      max-active: 50
      test-on-borrow: true

# Spring Security configurations are required for this application to work with the
# Karrostech Security dependency included in pom.xml.
security.jwt:
  tokenExpirationTime: ${security.jwt.duration.token} # Number of minutes
  refreshTokenExpTime: ${security.jwt.duration.refreshToken} # Minutes
  tokenIssuer: ${security.jwt.issuer}
  # base 64 encoded signing key
  tokenSigningKey: ${security.jwt.signature}
  secureAuthenticationEntryUrl: /api/**
  unsecurePathList: [/v2/api-docs/**, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /swagger-ui.html/**, /webjars/**, /swagger-resources/configuration/ui,
                     /swagger-resources/configuration/security, /manage/** ]

security.basic.enabled: false

hystrix.command.GetAllRoutes.execution.isolation.thread.timeoutInMilliseconds: 300000
hystrix.threadpool.GetAllRoutes.coreSize: 10
hystrix.threadpool.GetAllRoutes.maximumSize: 500
hystrix.threadpool.GetAllRoutes.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.convertToRoutePage.execution.isolation.thread.timeoutInMilliseconds: 300000
hystrix.threadpool.convertToRoutePage.coreSize: 10
hystrix.threadpool.convertToRoutePage.maximumSize: 500
hystrix.threadpool.convertToRoutePage.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.getRouteById.execution.isolation.thread.timeoutInMilliseconds: 600000
hystrix.threadpool.getRouteById.coreSize: 10
hystrix.threadpool.getRouteById.maximumSize: 500
hystrix.threadpool.getRouteById.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.deleteRouteById.execution.isolation.thread.timeoutInMilliseconds: 600000
hystrix.threadpool.deleteRouteById.coreSize: 10
hystrix.threadpool.deleteRouteById.maximumSize: 500
hystrix.threadpool.deleteRouteById.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.GetRouteByTenantId.execution.isolation.thread.timeoutInMilliseconds: 600000
hystrix.threadpool.GetRouteByTenantId.coreSize: 10
hystrix.threadpool.GetRouteByTenantId.maximumSize: 500
hystrix.threadpool.GetRouteByTenantId.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.searchRoutes.execution.isolation.thread.timeoutInMilliseconds: 600000
hystrix.threadpool.searchRoutes.coreSize: 10
hystrix.threadpool.searchRoutes.maximumSize: 500
hystrix.threadpool.searchRoutes.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.createOrUpdateRoutes.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.threadpool.createOrUpdateRoutes.coreSize: 10
hystrix.threadpool.createOrUpdateRoutes.maximumSize: 500
hystrix.threadpool.createOrUpdateRoutes.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.createOrUpdateRoutesForTenant.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.threadpool.createOrUpdateRoutesForTenant.coreSize: 10
hystrix.threadpool.createOrUpdateRoutesForTenant.maximumSize: 500
hystrix.threadpool.createOrUpdateRoutesForTenant.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.createOrUpdateRoute.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.threadpool.createOrUpdateRoute.coreSize: 10
hystrix.threadpool.createOrUpdateRoute.maximumSize: 500
hystrix.threadpool.createOrUpdateRoute.allowMaximumSizeToDivergeFromCoreSize: true
