server:
  port: 9394
spring.application.name: eventFanOutService

health:
  config:
    enabled: false

ribbon.eureka.enabled: true
logging.file: /opt/karros_tech/logs/@project.artifactId@-@project.version@.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: false

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.defaults.enabled: false 

kafka:
  applicationId: eventFanOutService
  consumer-group: eventsFanOut-p01usw2demo
  consumer:
    aggregateChanges: aggregateAVLEvents-p01usw2demo
    
tenant.vehicle.list: eb9a9b65-3810-4ffe-8cb2-fbb878ef9d1e,98100262-9d51-40f8-a1b2-4f27d01299db,47ba9b81-fe8c-4af6-a4d7-a92f53d369cc
