server:
  port: 9394
management:
  health:
    defaults:
      enabled: false
spring.application.name: eventFanOutService

ribbon.eureka.enabled: true
logging.file: /opt/karros_tech/logs/@project.artifactId@-@project.version@.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}
      healthcheck:
        enabled: true
drools:
  enabled: true

management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.elasticsearch.enabled: false

kafka:
  bootstrap-server: 10.20.20.121:9092
  applicationId: eventFanOutService
  consumer-group: eventsFanOut-consumer-group-p01use2dev1
  consumer:
    aggregateChanges: aggregateAVLEvents-p01use2dev

tenant.vehicle.list: 75692533-c3aa-4895-8703-10a3a4b0cd06,eb9a9b65-3810-4ffe-8cb2-fbb878ef9d1e,43800dac-9f95-40f2-9414-3dc58ac3234a
