# Property file for DevTest tier. Will be used if spring.profiles.active is set to "test"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.elasticsearch.enabled: false

#Accepted status values



# DB Configs
spring.cloud.stream.bindings:
  inputRAW:
    destination: run-agg-results-raw-test
    group: latestRead
    
  outputFS:
    destination: run-agg-results-test
   
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
spring.cloud.stream.kafka.streams.bindings:
  inputRAW:
    consumer: 
      applicationId: run-agg-results-raw-test    
spring.cloud.stream.kafka.bindings.inputRAW.consumer:
  autoCommitOnError: true    
         
spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${kafka-broker} #localhost #192.168.99.100
    applicationId: run-substitution-filter-sort-service-test
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit.interval.ms: 1000
      auto.offset.reset: earliest
      num:
        stream:
          threads: 3
numOfMessageToProcess: 20       
      