# Property file for local use. Will be used if spring.profiles.active is not set
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false

endpoints.sensitive: true
management.security.enabled: false
management.context-path: /

default.assignment.rules: TimeAvailability,vehicleOutService
substituion.assignment.rules: TimeAvailability,vehicleOutService

maxVehicleLimit: 5
kafka:
  schemaUrl: http://10.40.26.222:8081
  bootstrap: ${kafka-list-servers}
  vehicle:
    groupId: vehicleConsumer-vms-stage
    topic: vehicle-info-p01usw2stage
availabilityversion: 1.0
depotversion: 1.0
route.assignment.topic: route-assignment-p01usw2stage

# DB Configs
spring:
  redis:
    port: 6379
    host: redis-stage.usw2.karrostech.net
    database: 0
    password: MwMNehjHjN9Yta63xQq6gEcAQJ8h5G
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: rovars
        hbm2ddl:
          import_files:
        format_sql: true

  
edulog:
  datasource:
    url: jdbc:postgresql://db-stage.usw2.karrostech.net:5432/Edulog
    username: karros_prod_admin
    password: surr0nd3dDang3rN31ghb0rRhythm
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      max-idle: 50
      test-on-borrow: false
assignment.env: stage
default.tenant:holdarea: 3
default.search.allowedDays: 7

microservices:
  vms:
    serviceId: VEHICLEMANAGEMENTSERVICE
    getOutOfService:
      endpoint: http://${microservices.vms.serviceId}/api/v1/vms/graphql
      
graphiql:
  subscriptions:
     timeout: 30000
