ElasticSearchURL: ${elasticSearch.awsv7.url}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.defaults.enabled: false  

spring:
  redis:
    port: 6379
    host: redis-stage.usw2.karrostech.net
    database: 0
    password: MwMNehjHjN9Yta63xQq6gEcAQJ8h5G
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443  

kafka: 
  schemaUrl: http://10.40.26.222:8081
  applicationId: telematicsEventService-p01use2stage
  consumer-group: telematicsEventService-p01use2stage
  consumer:
    aggregateavltopic: aggregateAVLEvents-p01usw2stage
    routeassignmenttopic: route-assignment-p01usw2stage
    comparativeeventstopic: stop-detection-stage

    
async.enabled: enabled

consolidate.limit: 10

publish.env: stage
    
eventFilterMap: 

certificateFile: /edc3963789-certificate.pem.crt

privateKeyFile: /edc3963789-private.pem.key

default.response.key: id,busid,eventid,eventtime,location,vehicle_id,unitid,tenantid
additional.response.key: mileage,speed
