ElasticSearchURL: vpc-p01usw2stage-v7-fgczvvgqf5h7zwmoicajtnblua.us-west-2.es.amazonaws.com

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /
management.health.defaults.enabled: false  

spring:
  redis:
    host: redis-demo.usw2.karrostech.net
    port: 6379
    database: 0
    password: J4r8qXA44w6ZukWAtR6qU7wJcKvXTA
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443  

kafka:
  bootstrap-server: 10.40.26.222:9092
  schemaUrl: http://10.40.26.222:8081
  applicationId: telematicsEventService-p01use2stagetest
  consumer-group: telematicsEventServicetest-p01use2stage
  consumer:
    aggregateavltopic: aggregateAVLEvents-p01usw2stage
    routeassignmenttopic: route-assignment-p01usw2demo
    
async.enabled: enabled

consolidate.limit: 10

publish.env: stage
    
eventFilterMap: 

certificateFile: /edc3963789-certificate.pem.crt

privateKeyFile: /edc3963789-private.pem.key

default.response.key: id,busid,eventid,eventtime,location,vehicle_id,unitid,tenantid
additional.response.key: mileage,speed
