# Property file for local use. Will be used if spring.profiles.active is not set

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka-broker: 10.20.20.121:9092
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
    stream:
      kafka:
        streams:
          bindings:
            vehicleIntersectGeoFence:
              consumer:
                applicationId: geofenceMonitoringService-default
                startOffset: earliest
          binder:
            brokers: ${kafka-broker}
            applicationId: geofenceMonitoringService-default
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
              commit.interval.ms: 1000
      bindings:
        vehicleIntersectGeoFence:
          destination: aggregateAVLEvents-p01use2dev
          group: geofenceMonitoringService-default
          binder: kafka3
      binders:
        kafka3:
          type: kstream
kafka:
  bootstrap: ${kafka-broker}
  producer:
    publishNotificationRequest: publishNotificationRequest-p01use2dev

labelToAdd: geoFence
trackToAdd: Inside
statsToAdd: Some Stats Coming Soon!

# ES7 config
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10
  indexes:
    ignoredMessage: ignored_messages-*
    geofences: geofences
    
AlertZoneKeyValueStoreName: ${spring.cloud.stream.bindings.insideStateStore.destination}
keyValueStoreName: vehicleInterested
eventIdToBeProcessed: 2103,1
searchSize: 1000

alertZone:
  maximum_allowed_alert_zone_per_user_vehicle_source_app: 6
  minimum_time_interval: 300000
  
spring.redis.host: redis.use2.karrostech.net
spring.redis.port: 6379
spring.redis.database: 2
spring.redis.password: B8VZKjs4LL8a24Gq7zftw2M4eQvNmQ

spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 1
spring.redis.jedis.pool.max-idle: 8
