# Property file for DevTest tier. Will be used if spring.profiles.active is set to "test"
management.security.enabled: false
management.context-path: /
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

logging.level.root: INFO

# DB Configs
kafka-broker: ${kafka-list-servers}
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
    stream:
      kafka:
        streams:
          bindings:
            vehicleIntersectGeoFence:
              consumer:
                applicationId: geofenceMonitoringService-p01usw2stage
                startOffset: latest
          binder:
            brokers: ${kafka-broker}
            applicationId: geofenceMonitoringService-p01usw2stage
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
              commit.interval.ms: 1000
      bindings:
        vehicleIntersectGeoFence:
          destination: aggregateAVLEvents-p01usw2stage
          group: geofenceMonitoringService-p01usw2stage
      binders:
        kafka3:
          type: kstream
kafka:
  bootstrap: ${kafka-broker}
  producer:
    publishNotificationRequest: publishNotificationRequest-p01usw2stage

labelToAdd: geoFence
trackToAdd: Inside
statsToAdd: Some Stats Coming Soon!

AlertZoneKeyValueStoreName: ${spring.cloud.stream.bindings.insideStateStore.destination}
keyValueStoreName: vehicleInterested
eventIdToBeProcessed: 2103,1
searchSize: 1000

spring.redis.host: redis-stage.usw2.karrostech.net
spring.redis.port: 6379
spring.redis.password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAE2sKTlQDSfimxDjpGVz68IAAAAfDB6BgkqhkiG9w0BBwagbTBrAgEAMGYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8e85GsIHhxUIlHd9AgEQgDlDDnuWEINmeSyF3kloXQFrIrnihVq8/itQMyKaN/yqM1X/VVLE61mqv8K2xjeBrHm9edkXR/laE80='

# Custom redis factory
spring.redis.geofence.host: ${spring.redis.host}
spring.redis.geofence.port: ${spring.redis.port}
spring.redis.geofence.database: 2
spring.redis.geofence.password: ${spring.redis.password}

spring.redis.tenant.host: ${spring.redis.host}
spring.redis.tenant.port: ${spring.redis.port}
spring.redis.tenant.database: 0
spring.redis.tenant.password: ${spring.redis.password}
# Custom redis factory

spring.redis.jedis.pool.max-active: 50
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 10
spring.redis.jedis.pool.max-idle: 30

# ES7 config
es:
  url: ${elasticSearch.awsv7.url}
  protocol: https
  username: ${elasticSearch.awsv7.username}
  password: ${elasticSearch.awsv7.password}
  port: ${elasticSearch.awsv7.port}
  connectionTimeout: 2000
  socketTimeout: 3000
  parallelThreads: 10
  indexes:
    ignoredMessage: ignored_messages-*
    geofences: geofences

alertZone:
  maximum_allowed_alert_zone_per_user_vehicle_source_app: 6		
  minimum_time_interval: 300000

timeToIgnoredPushNotification: 3600000		
timeToStillSendPushNotification: 900000
