server:
  port: 9393
kafka: 
  bootstrap-server: 10.40.26.222:9092
  applicationId: comparator-filter-validation-stage
  consumer-group: comparator-filter-validation-stageusw
  consumer:
    aggregateEvent: aggregateAvlEvents-test-stage


tenant.enabled.list: ba82b332-dcad-442b-969f-f989a9a1d5ef,65b9371b-10e1-4c85-b2a3-a271628b0345,47523cb9-2e1e-4072-8825-4ad939d3983a,2924b186-7615-49dd-b23a-867080f97f15,a9251698-daf3-472f-8d83-83439b5983f2
eventId.enabled: 1,2103,2001,2140,2002,2141,2005,2152,2006,2153,2160,2150,2151
speed.limit: 5
comparator.output.topic: comparatoranalysis-input-stage
comparator.input.topic: aggregateAvlEvents-test-stage


bootstrap.server: 10.40.26.222:9092
client.groupId: comparaor-event-filter-analyzer

management.endpoints.web.exposure.include: "*"
