server:
  port: 9393
kafka: 
  bootstrap-server: 10.40.26.222:9092
  applicationId: comparator-filter-validation-demo
  consumer-group: comparator-filter-validation-demousw
  consumer:
    aggregateEvent: aggregateAVLEvents-p01usw2demo


tenant.enabled.list: 59ff9686-097c-49cd-ad40-4b07ca6d4611,47ba9b81-fe8c-4af6-a4d7-a92f53d369cc,ba82b332-dcad-442b-969f-f989a9a1d5ef,65b9371b-10e1-4c85-b2a3-a271628b0345,eb9a9b65-3810-4ffe-8cb2-fbb878ef9d1e
eventId.enabled: 1,2103,2001,2140,2002,2141,2005,2152,2006,2153,2160,2150,2151
speed.limit: 5
sensor.events: 2001,2140,2002,2141,2005,2152,2006,2153,2160,2150,2151
comparator.output.topic: comparatoranalysis-input-p01usw2demo
comparator.input.topic: aggregateAVLEvents-p01usw2demo


bootstrap.server: 10.40.26.222:9092
client.groupId: comparaor-event-filter-analyzerdemo

management.security.enabled: false
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: "*"
management.endpoints.web.base-path: /

es:
  url: 8c86d819876e464dbbb6823dbf2f49c6.us-west-2.aws.found.io
  username: elastic
  password: PMFuUgkRh8bIAJU4wro3qYX6
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 9243
  query:
    detectRadius: 10m
    maxHitThreshold: 30
    eventSearchWindow: 10m
