# Property file for DevTest tier. Will be used if spring.profiles.active is set to "test"

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

kafka:
  bootstrap: ${kafka.bootstrap-server}
  consumer:
    groupId: production-live-event-conversion
    topic: avlEvents-p01usw1prod

index: realtimevehiclesevents
type: doc
ElasticSearchURL: vpc-p01usw1prod-mk5xmhey72i44thke3onjjacda.us-west-1.es.amazonaws.com
usernamee:
password:
port: 443
parallelESCountThreads: 500     
usernameElastic:
passwordElastic: