comparator.input.topic: comparatoranalysis-input-dev
comparator.output.topic: comparator-geosearch-outputdev
bootstrap.server: 10.20.20.121:9092
client.groupId: comparaor-analysis-dev-cons
detection.output.topic: stop-detection-dev

score.rfid.event: 100
score.dooropen.event: 50
score.stoparm.event: 50
score.wheelchair.event: 50
score.gps.accurate.event: 20
score.gps.delayed.event: 10

max.delayed.allowed: 3
eventId.enabled: 1,2103,2001,2140,2002,2141,2005,2152,2006,2153,2160,2150,2151
unscheduled.events: 2001,2140,2002,2141,2005,2152,2006,2153,2160,2150,2151
ksql.server.host: 10.20.20.48
ksql.server.port: 8088
ksql.table.name: COMPARATOR_SCORE_TABLE_MVWR_DEV


ElasticSearchURL: vpc-p01use2dev-7-3ga6y7r4qsd4mzrwyyrjtnpwra.us-east-2.es.amazonaws.com

kafka: 
  bootstrap-server: 10.40.26.222:9092
  applicationId: comparator-filter-validation-localusw1
  consumer-group: comparator-filter-validation-localusw1
  consumer:
    scheduleevent: COMPARATOR_WAYPOINT_SCORE_MVW_P01USW2STAGE
    unscheduleevent: unscheduled-event-p01usw2stage

es:
  username:
  password:
  protocol: https
  connectionTimeout: 10000
  socketTimeout: 60000
  parallelESCountThreads: 100
  port: 443
  query:
    detectDistanceMeters: 10
    maxHitThreshold: 10
    eventSearchWindow: 30m
