eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

spring:
  jpa:
    properties:
      hibernate:
        default_schema: account
        
edulog:
  datasource:
    url: ${rds.dataSource.url&&&&&}
    username: ${rds.dataSource.username}
    password: ${rds.dataSource.password}
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 5
      test-on-borrow: true
es:
  ElasticSearchURL: ${elasticSearch.cloud.url}
  username: ${elasticSearch.cloud.username}
  password: ${elasticSearch.cloud.password}
  port: ${elasticSearch.cloud.port}
  parallelESCountThreads: 100

kafka:
  bootstrap-server: ${kafka-broker}
  producer:
    changedAccountSetting: changedAccountSetting-p01use2dev

server:
  domain: https://accounts-dev.edulog.cloud