eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

spring:
  jpa:
    properties:
      hibernate:
        default_schema: account


es:
  ElasticSearchURL: ${elasticSearch.cloud.urlaB}
  username: ${elasticSearch.cloud.username}
    password: ${elasticSearch.cloud.password}
es:
  ElasticSearchURL: ${elasticSearch.cloud.urlaB}
  username: ${elasticSearch.cloud.username}
  password: ${elasticSearch.cloud.password}
  port: ${elasticSearch.cloud.port}
  parallelESCountThreads: 100

kafka:
  bootstrap-server: ${kafka-broker}
  producer:
    changedAccountSetting: changedAccountSetting-p01usw2demo

server:
  domain: https://accounts-demo.edulog.cloud