# Property file for DevTest tier. Will be used if spring.profiles.active is set to "test"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-prod.usw1.karrostech.net:1112/eureka/,http://eureka02-p01-prod.usw1.karrostech.net:1112/eureka/


# DB Configs
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: master_data
        hbm2ddl:
          import_files:
      
testindex: testhistoricaldata
testtype: testplandata
ElasticSearchURL: vpc-p01usw1prod-mk5xmhey72i44thke3onjjacda.us-west-1.es.amazonaws.com
snapShotIndex: plandata
snapShotType: _doc
changeLogIndex: plandatachangelog
changeLogType: _doc
esUser:
password:
port: 443
parallelESCountThreads: 100
connectionTimeout: 50000
socketTimeout: 60000
maxScrollSize: 10000
defaultTimeOutinSec: 120
index: plandatahistory
type: doc
ESconnectionRequestTimeout: -1

# Spring Security configurations are required for this application to work with the
# Karrostech Security dependency included in pom.xml.
security.jwt:
  tokenExpirationTime: 120 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://karrostech.com
  # base 64 encoded signing key
  tokenSigningKey: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsh0GXHEy3S3jOX9QXXT8yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDWTMtLq5qBNuvpYAgEQgDvEFsvknk7vamQJiB5wJmwbF570MckoCVEqD8O7MVwpzzbK8pdXJ4dMDfFUeMcWL+eE/SaCae9u6QX4cQ=='
  secureAuthenticationEntryUrl: /api/**/students/**
  unsecurePathList: [/v2/api-docs/**, /configuration/ui, /swagger-resources, /configuration/security, /swagger-ui.html, /swagger-ui.html/**, /webjars/**, /swagger-resources/configuration/ui,
                     /swagger-resources/configuration/security, /manage/** ]

hystrix.command.PostPlanDataHistory.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.PostPlanDataHistory.coreSize: 10
hystrix.threadpool.PostPlanDataHistory.maximumSize: 500
hystrix.threadpool.PostPlanDataHistory.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.GetPlanDataHistory.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.GetPlanDataHistory.coreSize: 10
hystrix.threadpool.GetPlanDataHistory.maximumSize: 500
hystrix.threadpool.GetPlanDataHistory.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.GetMetaDataPlanDataHistory.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.GetMetaDataPlanDataHistory.coreSize: 10
hystrix.threadpool.GetMetaDataPlanDataHistory.maximumSize: 500
hystrix.threadpool.GetMetaDataPlanDataHistory.allowMaximumSizeToDivergeFromCoreSize: true

hystrix.command.DeletePlanDataHistory.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.DeletePlanDataHistory.coreSize: 10
hystrix.threadpool.DeletePlanDataHistory.maximumSize: 500
hystrix.threadpool.DeletePlanDataHistory.allowMaximumSizeToDivergeFromCoreSize: true

kafka:
  bootstrap: ${kafka-broker}
  groupId: prodchangedPlanRouteGroup
  producer:
    topic: changedPlanRoute-p01usw1prod
  retries: 3
  publish:
    enabled: true
