postgres:
  url: db-prod.usw1.karrostech.net
  port: 5432
  database: Edulog
  username_plan_ingest_monitoring: plan_ingest_monitoring
  password_plan_ingest_monitoring: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGG7oaSp7ADQhJvVAqM2mPHAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrDthcY9ZmeBZauneAgEQgCryVFly3JgRc3JNbNMRtzezyXiDQUP/3cZNrNu+iBFKXoMPXQEZnwhB+kI='


elastic_search_aws:
  timeout: 20s 
  
elastic_search_co:
  timeout: 20s

# Drop Time must be greater than Alert Time.
telematics_monitor:
  alert_time: 50  # Minutes
  drop_time: 60   # Minutes
