postgres:
  url: db-prod.usw1.karrostech.net
  port: 5432
  database: Edulog
  username_plan_ingest_monitoring: plan_ingest_monitoring
  password_plan_ingest_monitoring: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGG7oaSp7ADQhJvVAqM2mPHAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrDthcY9ZmeBZauneAgEQgCryVFly3JgRc3JNbNMRtzezyXiDQUP/3cZNrNu+iBFKXoMPXQEZnwhB+kI='


elastic_search_aws:
  timeout: 20s 
  
elastic_search_co:
  timeout: 20s

# Drop Time must be greater than Alert Time.
telematics_monitor:
  alert_time: 50  # Minutes
  drop_time: 60   # Minutes

gateway_url: https://gateway-p01-prod.usw1.karrostech.net
mission_control_gateway: https://missioncontrolgateway-p01-prod.usw1.karrostech.net
elastic_search_aws_v7:
  url: vpc-p01usw1prod3-v7-6lhyyd46hyr5bous6vqtykpdce.us-west-1.es.amazonaws.com
