postgres:
  url: db-stage.usw2.karrostech.net
  port: 5432
  database: Edulog
  username_plan_ingest_monitoring: plan_ingest_monitoring
  password_plan_ingest_monitoring: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAH4+RYgPpENeNx1E/Rpz0GpAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBia1+2WlZffZTjaJAgEQgCq10S6CadVLbkRzTZWt4pSMvhiLg50Q+CBj9e2OfZ2NMaCncRt+c1XWWMg='


elastic_search_aws:
  timeout: 20s 
  
elastic_search_co:
  timeout: 20s

# Drop Time must be greater than Alert Time.
telematics_monitor:
  alert_time: 470  # Minutes
  drop_time: 480   # Minutes

gateway_url: https://gateway-p01-stage.usw2.karrostech.net
