postgres:
  url: db-demo.usw2.karrostech.net
  port: 5432
  database: Edulog
  username_plan_ingest_monitoring: plan_ingest_monitoring
  password_plan_ingest_monitoring: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAFrwtihpc03Tjde0ipUK/qTAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdCYlOl0oG05qw7vSAgEQgCtpjxshjtnoEeGP41IHdYhxLTBCRiDr/ur3US8Tel3Ey3CyMszg2yK7Z58c'


elastic_search_aws:
  timeout: 20s 
  
elastic_search_co:
  timeout: 20s

# Drop Time must be greater than Alert Time.
telematics_monitor:
  alert_time: 470  # Minutes
  drop_time: 480   # Minutes

gateway_url: https://gateway-p01-demo.usw2.karrostech.net
