endpoint-status:
  ksqldb-dev: 
    description: "Used to aggregate values within kafka for services like comparative analysis"
    environment: dev
    service: ksqldb
    url: "10.20.20.48:8088/healthcheck"
  ksqldb-prod: 
    description: "Used to aggregate values within kafka for services like comparative analysis"
    environment: prod
    service: ksqldb
    url: "10.40.26.73:8088/healthcheck" 
  schema-registry: 
    description: "Stores the avro schema"
    environment: prod
    service: schema-registry
    url: "10.40.26.222:8081/subjects"    
