eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01-p01-prod.usw1.karrostech.net:1112/eureka/,http://eureka02-p01-prod.usw1.karrostech.net:1112/eureka/

spring.cloud.stream.bindings:
  input:
    destination: aggregateAVLEvents-p01usw1prod
  output:
    destination: run-sub-es-results-p01usw1prod

spring.cloud.stream.kafka.streams:
  binder:
    application-id: RUNDETECTIONSERVICE-p01usw1prod
    brokers: ${kafka.bootstrap-server}

ElasticSearchURL: ${elasticSearch.awsv7.url}
