eureka:
  hostname: ${eureka.instances}
  service_port: 80
  enabled: false

ribbon.eureka.enabled: false

server:
  port: 9090

sidecar:
  host: localhost
  port: 5000
  slug: health
  health-uri: http://${sidecar.host}:${sidecar.port}/${sidecar.slug}
  home-page-uri: http://${sidecar.host}}:${sidecar.port}/

auth:
  clientId: ${auth.credentials.clientId}
  clientSecret: ${auth.credentials.clientSecret}
  grantType: client_credentials
  scope: Parent Portal

app_config:
  concurrent_count: 8
  log_level: "DEBUG"
  key: ${aesKey}

elastic_search:
  url: ${elasticSearch.coreServices.url}
  port: ${elasticSearch.coreServices.port}
  password: ${elasticSearch.coreServices.password}
  username: ${elasticSearch.coreServices.username}
  index_base: zonarfetchsource
  status_index: ${elastic_search.index_base}.status
  raw_index: ${elastic_search.index_base}.raw


gateway:
  url: https://gateway-p01-dev.use2.karrostech.net

log_level: DEBUG
