logging.file: /opt/karros_tech/logs/@project.artifactId@-@project.version@.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

# DB Configs
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: public
        hbm2ddl:
          import_files:

# AWS Dev DB
edulog:
  datasource:
    url: ${rds.dataSource.url}
    username: ${rds.dataSource.username}
    password: ${rds.dataSource.password}
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: select 1;
    tomcat:
      max-wait: 10000
      initialSize: 2
      max-active: 50
      test-on-borrow: true

authUrl: https://gateway-p01-dev.use2.karrostech.net/api/v1/signin
baseUrls:
  studentTrip: https://gateway-p01-dev.use2.karrostech.net/api/v2/studenttrips
