eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

ribbon.eureka.enabled: false

management:
  health:
    redis:
      enabled: false

zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  ribbonIsolationStrategy: THREAD
  routes:
    accounts:
      path: /api/*/accounts/**
      serviceId: ACCMGMTSERVICE
      stripPrefix: false
    accountsPage:
      path: /api/*/pages/accounts/**
      serviceId: ACCMGMTSERVICE
      stripPrefix: false
    login:
      path: /api/v1/signin/**
      serviceId: AUTHSERVICE
      stripPrefix: false
    events:
      path: /event/**
      serviceId: EVENTQUERYWSAPI
    events_v1:
      path: /api/0.1/events/**
      serviceId: VEHICLELIVEEVENTSERVICE
      # serviceId: EVENTQUERYWSAPI
      stripPrefix: false
    events_v2:
      path: /api/0.2/events/**
      serviceId: VEHICLELIVEEVENTSERVICE
      # serviceId: EVENTQUERYWSAPI
      stripPrefix: false
    vehicleStatus:
      path: /api/v1/vehicleStatus/**
      serviceId: VEHICLELIVEEVENTSERVICE
      # serviceId: EVENTQUERYWSAPI
      stripPrefix: false
    vehicles:
      path: /api/*/vehicles/**
      serviceId: VEHICLEQUERYWSAPI
      stripPrefix: false
    vehicles2:
      path: /api/v2/tenants/*/vehicles/**
      serviceId: VEHICLEQUERYWSAPI
      stripPrefix: false
    vehicles3:
      path: /api/v3/vehicletenantmappings/devices/**
      serviceId: VEHICLEQUERYWSAPI
      stripPrefix: false
    tenants:
      path: /api/*/tenants/**
      serviceId: TENANTSERVICE
      stripPrefix: false
    tenantsettings:
      path: /api/*/tenantsettings/**
      serviceId: TENANTSERVICE
      stripPrefix: false
    districts:
      path: /api/*/districts/**
      serviceId: TENANTSERVICE
      stripPrefix: false
    schools:
      path: /api/v*/schools/**
      serviceId: TENANTSERVICE
      stripPrefix: false
    transportation:
      path: /api/v1/students/*/trips/**
      serviceId: TRANSPORTATIONLOOKUPSERVICE
      stripPrefix: false
    transportation2:
      path: /api/v2/students/trips**
      serviceId: TRANSPORTATIONLOOKUPSERVICE
      stripPrefix: false
    people:
      path: /api/v*/people/**
      serviceId: PERSONSERVICE
      stripPrefix: false
    students:
      path: /api/v*/students/**
      serviceId: PERSONSERVICE
      stripPrefix: false
    insights:
      path: /insight/**
      serviceId: INSIGHTWSAPI
    routeAssignments:
      path: /api/*/routeAssignments/**
      serviceId: ROUTEVEHICLEDRIVERMAPPINGSERVICE
      stripPrefix: false
    studentTriprouteAssignment:
      path: /api/v1/studenttriprouteassignment/**
      serviceId: STUDENTTRIPSERVICE
      stripPrefix: false
    studentTrips:
      path: /api/v*/studenttrips/**
      serviceId: STUDENTTRIPSERVICE
      stripPrefix: false
    aggPlanDataService:
      path: /api/v1/agg/routes/**
      serviceId: AGGPLANDATASERVICE
      stripPrefix: false
    planDataHistoryService:
      path: /api/v1/planDataHistory/**
      serviceId: planDataHistoryService
      stripPrefix: false
    driverDirectionsService:
      path: /api/v1/drivingDirections/**
      serviceId: driverDirectionsService
      stripPrefix: false
    vehicleLiveEvent:
      path: /api/v*/vehicleliveevents/**
      serviceId: VEHICLELIVEEVENTSERVICE
      stripPrefix: false
    vehicleHistoricalEvents:
      path: /api/v*/vehiclehistoricalevents/**
      serviceId: VEHICLEHISTORICALEVENTSERVICE
      stripPrefix: false
    accessRequests:
      path: /api/*/studentAccessRequests/**
      serviceId: ACCESSMANAGEMENTSERVICE
      stripPrefix: false
    accessRequestsById:
      path: /api/*/users/*/studentAccessRequests/**
      serviceId: ACCESSMANAGEMENTSERVICE
      stripPrefix: false
    missioncontrol:
      path: /api/*/mc/**
      serviceId: MISSIONCONTROLWSAPI
      stripPrefix: false
    routeServices:
      path: /api/v*/plan/routes/**
      serviceId: ROUTESERVICE
      stripPrefix: false
    pathServices:
      path: /api/v*/paths/**
      serviceId: PATHSERVICE
      stripPrefix: false
    systemManagement:
      path: /api/*/sm/**
      serviceId: SYSTEMMANAGEMENTWSAPI
      stripPrefix: false
    notificationService:
      path: /api/*/notification/**
      serviceId: NOTIFICATIONSERVICE
      stripPrefix: false
    subscriptions:
      path: /api/*/subscriptions/**
      serviceId: NOTIFICATIONSERVICE
      stripPrefix: false
    registrationCodes:
      path: /api/*/registrationcodes/**
      serviceId: ACCESSMANAGEMENTSERVICE
      stripPrefix: false
    accessmanagementservice:
      path: /api/*/accessrequest/**
      serviceId: ACCESSMANAGEMENTSERVICE
      stripPrefix: false
    accessmanagementservicev2:
      path: /api/*/accessrequests/**
      serviceId: ACCESSMANAGEMENTSERVICE
      stripPrefix: false
    transportationRequests:
      path: /api/v*/transportationRequests/**
      serviceId: TRWSAPI
      stripPrefix: false
    pp:
      path: /api/v*/pp/**
      serviceId: PPWSAPI
      stripPrefix: false
    ingestionmanagementservice:
      path: /api/*/ingestion/**
      serviceId: INGESTIONMANAGEMENTSERVICE
      stripPrefix: false
    substitutionWSAPI:
      path: /api/*/substitutions/**
      serviceId: SUBSTITUTIONWSAPI
      stripPrefix: false
    ridershipAccessCardsManagementService:
      path: /api/*/accesscards/**
      serviceId: RIDERSHIPMANAGEMENTSERVICE
      stripPrefix: false
    ridershipStudentVehicleLinkedManagementService:
      path: /api/*/ridership/**
      serviceId: RIDERSHIPMANAGEMENTSERVICE
      stripPrefix: false
    ridershipStudentAccessCardMappingManagementService:
      path: /api/*/studentaccesscardmappings/**
      serviceId: RIDERSHIPMANAGEMENTSERVICE
      stripPrefix: false
    ridershipMonitoringService:
      path: /api/*/scanhistories/**
      serviceId: RIDERSHIPMONITORINGSERVICE
      stripPrefix: false
    accountService:
      path: /api/*/accountsettings/**
      serviceId: ACCOUNTSERVICE
      stripPrefix: false
    accountManagement:
      path: /api/*/accountManagement/**
      serviceId: ACCOUNTSERVICE
      stripPrefix: false
    geofences:
      path: /api/*/geofences/**
      serviceId: GEOFENCEALERTMANAGEMENTSERVICE
      stripPrefix: false
    auditService:
      path: /api/*/audit/**
      serviceId: AUDITSERVICE
      stripPrefix: false
    telematicsSubscriptionService:
      path: /api/*/telematics/**
      serviceId: TELEMATICSSUBSCRIPTIONSERVICE
      stripPrefix: false
    vehicleManagementService:
      path: /api/*/vms/**
      serviceId: VEHICLEMANAGEMENTSERVICE
      stripPrefix: false
    inventoryService:
      path: /api/*/equipment/**
      serviceId: INVENTORYSERVICE
      stripPrefix: false
    schedulerManagementService:
      path: /api/*/scheduler/**
      serviceId: SCHEDULERMANAGEMENTSERVICE
      stripPrefix: false
  retryable: true
# API Keys that are acceptable
validApiKeys: ${apiKeys}

audit:
  loggedBy: ${spring.application.name}
  enabled: true
  methods: POST,PUT,DELETE,PATCH, GET
  defaultIgnoredEndpoints:
  defaultStoreResponseBody: true
  defaultStoreRequestBody: true
  #This header will be added before Zuul routing, but Zuul auto converts to lower case, so the value should be in lower case
  xTrkHeaderKeyName: x-trk-id
  customRequests:
    -
      endpoints: /api/v1/vehicleStatus, /api/0.2/events/vehicleId?vehicleId=
      methods: GET
      enabled: false
      storeRequestBody: true
      storeResponseBody: false
    -
      endpoints: /search, /bulksearch, /export
      methods: POST, GET
      enabled: true
      storeRequestBody: true
      storeResponseBody: false
