eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

management:
  health:
    redis:
      enabled: false

# API Keys that are acceptable
validApiKeys: ${apiKeys}

audit:
  loggedBy: ${spring.application.name}
  enabled: true
  methods: POST,PUT,DELETE,PATCH, GET
  defaultIgnoredEndpoints:
  defaultStoreResponseBody: true
  defaultStoreRequestBody: true
  #This header will be added before Zuul routing, but Zuul auto converts to lower case, so the value should be in lower case
  xTrkHeaderKeyName: x-trk-id
  customRequests:
    -
      endpoints: /api/v1/vehicleStatus, /api/0.2/events/vehicleId?vehicleId=
      methods: GET
      enabled: false
      storeRequestBody: true
      storeResponseBody: false
    -
      endpoints: /search, /bulksearch, /export
      methods: POST, GET
      enabled: true
      storeRequestBody: true
      storeResponseBody: false