eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.instances}

spring:
  cloud:
    stream:
      kafka:
        streams:
          bindings:
            liveEvent:
              consumer:
                applicationId: vehicleStatusService-p01usw2demo
                startOffset: latest
          binder:
            brokers: ${kafka-broker}
            applicationId: vehicleStatusService-p01usw2demo
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
              commit.interval.ms: 1000
      bindings:
        liveEvent:
          destination: aggregateAVLEvents-p01usw2demo
          binder: kstream
      binders:
        kstream:
          type: kstream

spring.redis.host: redis-demo.usw2.karrostech.net
spring.redis.port: 6379
spring.redis.database: 4
spring.redis.password: '{cipher}AQICAHhwRLH9r5EwhXiI7DKT7Bu2NJ2KcnE9k/MeZthez+G0EAGsP0dcMRb2ccR0M5OZ9u2QAAAAfDB6BgkqhkiG9w0BBwagbTBrAgEAMGYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5ZwTH/yi3i+KkGDHAgEQgDlZb3mBKRe9lvZ4savziOdKl57sdyDy7zH0flgd3GuayrFVgZ6X0It90pekXlX6ccRN3fTO0+dLXuE='

spring.redis.jedis.pool.max-active: 50
spring.redis.jedis.pool.max-wait: 5000ms
spring.redis.jedis.pool.min-idle: 10
spring.redis.jedis.pool.max-idle: 30

redis:
  channel:
    enable: false
    tenant_prefix: TENANT_

processed:
  events: 2103,1

