# Disable eureka
ribbon.eureka.enabled: false

# Kafka config
kafka:
  bootstrap-server: 10.20.20.121:9092
  consumer:
    studentTripChange: changeStudentTrip-p01use2dev_v2
    appSyncRequestTopic: appSyncRequest-p01use2dev
  producer:
    appSyncRequestTopic: appSyncRequest-p01use2dev
  consumer-group: appsyncNotifier-p01use2dev

microservices:
  accessManagement:
    serviceId: ACCESSMANAGEMENTSERVICE
    searchEmailByStudentAndApp: http://${microservices.accessManagement.serviceId}/api/v1/studentAccessRequests/requesterEmailsByStudentIds/search

appSync:
  url: https://b6mzcbuisrf73nxxyvpyaha3ha.appsync-api.us-east-2.amazonaws.com/graphql
  apiKey: da2-loqufft5a5ecrcmcbje3twxeqe
