# Eureka
ribbon.eureka.enabled: true

# Kafka config
kafka:
  bootstrap-server: ${kafka-list-servers}
  consumer:
    studentTripChange: changeStudentTrip-p01usw1prod_v2
  producer:
    appSyncRequestTopic: appSyncRequest-p01usw1prod
  consumer-group: appsyncNotifier-p01usw1prod

microservices:
  accessManagement:
    serviceId: ACCESSMANAGEMENTSERVICE
    searchEmailByStudentAndApp: http://${microservices.accessManagement.serviceId}/api/v1/studentAccessRequests/requesterEmailsByStudentIds/search